### ISSUE TITLE
Build fails with confusing error

### ISSUE THREAD

**Issue by seanrsain** [bflad/tfproviderlint-github-action#2]
When trying to run the GitHub Action in provider repo I am getting the following error: `tfproviderlint: ./... matched no packages`

I believe I have set up my yaml file correctly:

```
# This is a basic workflow to run tfproviderlint
name: tfproviderlint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out tfproviderlint repository and runs tfproviderlint ./...
    - uses: bflad/tfproviderlint-github-action@master
      with:
        args: ./...
```

Not sure what I am doing wrong. Any help would be appreciated!

**Comment by bflad** [comment]
Hi @seanrsain 👋 I believe you need to checkout your code first, e.g.

```
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2.0.0    
    - uses: bflad/tfproviderlint-github-action@master
      with:
        args: ./...
```
