### ISSUE TITLE
go: cannot find GOROOT directory

### ISSUE THREAD

**Issue by Integralist** [bflad/tfproviderlint-github-action#4]
This is the setup I'm using (shortened for brevity)...

```yaml
- name: Install Go
  uses: actions/setup-go@v2
  with:
    go-version: 1.17.x
- name: Lint
  uses: bflad/tfproviderlint-github-action@master
  with:
    args: ./...
```

The error I'm seeing...

```
tfproviderlint: err: exit status 2: stderr: go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.17.13/x64
```

The `setup-go` action reports:

```
GOROOT="/opt/hostedtoolcache/go/1.17.13/x64"
```

Which matches the expectation of this action.
